import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/redux/store/reduxProvider";
import Navbar from "@/components/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <div className="max-w-4xl mx-auto">
            <header>
              <Navbar />
            </header>
            <main>
              {children}
            </main>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
